### PR TITLE
Track station mode connect and disconnect events

### PR DESCRIPTION
**Pull request by ConnorRigby**

### CODE REVIEW

**Comment by fhunleth** [comment]
I almost did this, but then wasn't sure of a use case!

There's a section towards the end of the README.md where I document the properties. Look for the WiFi section. 

This is making me think that the property should be `["interface", ifname, "wifi", "clients"]` and that `"access_points"` would be moved under the `"wifi"` group too.

**Comment by ConnorRigby** [comment]
@fhunleth i'm fine with moving those properties. Should i open a different PR moving the other property before updating this one?

**Comment by fhunleth** [comment]
Whatever is easier for you. Not a big deal to me at this stage of the project.

**Comment by ConnorRigby** [comment]
@fhunleth updated. LMK if we need anything else

**Comment by fhunleth** [comment]
LGTM. Once CI completes, I'll merge.

**Comment by ConnorRigby** [comment]
@fhunleth i updated to make coverage not be angry. Ready whenever

**Comment by fhunleth** [comment]
Thanks. It's important that code coverage of our networking stack for Nerves be higher than nerves_hub_web. Because reasons and irony.

**Pull request merged**
