### PR TITLE
Add helper to deconfigure an interface

### PR DESCRIPTION
**Pull request by ConnorRigby**
I find myself writing this helper for every project that uses VintageNet, so i thought i'd just put it here.

### CODE REVIEW

**Comment by fhunleth** [comment]
I like this. The only hesitation is that if you `deconfigure` and call `configured_interfaces/0`, you'll still get the interface. What do you think of adding a filter on `configured_interfaces/0` to prune it of everything with a `Null` configuration?

In case you're wondering why I never implemented a complete delete, the reason is that I ran into a race condition with a back-to-back delete and re-add at one point. I thought that the benefit of removing a configuration was so small that it wasn't worth maintaining.

**Comment by ConnorRigby** [comment]
>  What do you think of adding a filter on configured_interfaces/0 to prune it of everything with a Null configuration?

This seems straightforward enough. Update incoming

**Comment by fhunleth** [comment]
Oh no, coverage has dropped below 80% and that changes the badge color. Could you add a short unit test?

**Comment by ConnorRigby** [comment]
@fhunleth i fixed the test i broke. Should i add another? Coverage seems to be right on the cusp of 80%

**Comment by fhunleth** [comment]
Yeah, it would be good to have at least one call to `deconfigure` in the unit tests.

**Comment by fhunleth** [comment]
Great! And thanks for adding the test.

**Pull request merged**
