### PR TITLE
Delete lines that don't have contents

### PR DESCRIPTION
**Pull request by ConnorRigby**
I don't really know how i feel about this. While working on another feature, i noticed that not supplying _every_ key leaves a _ton_ newlines, which leads to all of those newlines needing to be in the tests.

### CODE REVIEW

**Comment by fhunleth** [comment]
I haven't been thinking too hard about how things get done internally. However, my instinct would be manage the config as iodata and use a list at the top level. Then options could add an item to the list or not and then it would all be flattened at the end.

**Comment by ConnorRigby** [comment]
Oh i like the idea about IOdata much better. Let me try that.

**Comment by ConnorRigby** [comment]
@fhunleth how do you feel about this now? (i can squash it, i just wanted to maintain history for the sake of this PR)

**Comment by fhunleth** [comment]
Looks better to me!

**Comment by ConnorRigby** [comment]
Okay i removed that first idea. Ready for merge i think.

**Pull request merged**
