### PR TITLE
Add support for WPA-EAP networks

### PR DESCRIPTION
**Pull request by ConnorRigby**

### CODE REVIEW

**Comment by fhunleth** [comment]
That was quick!

**Comment by fhunleth** [comment]
Also, sorry for the PropertyTable API change... I decided to move the important stuff under VintageNet for ease of documentation and to make it easier to pull out/change in the future.

**Comment by fhunleth** [comment]
Merged. I know nothing about WPA-EAP. Do you have a little text that could be put in the README.md under the WiFi section?

**Comment by ConnorRigby** [comment]
@fhunleth yep was just gonna add that. Got more coming

**Pull request merged**
